# Generated by Django 4.2.5 on 2023-11-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='photos_root/'),
        ),
    ]
