# Generated by Django 4.2.5 on 2024-04-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_last_login_alter_post_photo_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='stories_videos/'),
        ),
    ]
