# Generated by Django 4.2.5 on 2024-04-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_stories_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
