# Generated by Django 4.2.5 on 2024-04-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_stories_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='main.user'),
        ),
    ]
