# Generated by Django 4.2.5 on 2024-05-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_message_chat_remove_message_sender_post_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_setting', models.TextField(max_length=255)),
                ('stories_settings', models.TextField(max_length=255)),
                ('comments_settings', models.TextField(max_length=255)),
                ('black_list', models.ManyToManyField(blank=True, related_name='blacklist_users', to='main.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='main.user')),
            ],
        ),
    ]
