# Generated by Django 4.2.5 on 2024-05-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='account_setting',
        ),
        migrations.AddField(
            model_name='settings',
            name='account_settings',
            field=models.TextField(default='All', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='comments_settings',
            field=models.TextField(default='All', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='stories_settings',
            field=models.TextField(default='All', max_length=255),
        ),
    ]
