# Generated by Django 4.2.5 on 2024-05-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_settings_account_setting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='black_list',
        ),
    ]
