# Generated by Django 4.2.5 on 2024-05-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_settings_black_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='black_list',
            field=models.ManyToManyField(related_name='black_list_users', to='main.user'),
        ),
    ]
