# Generated by Django 4.2.2 on 2023-06-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Никнейм')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('email', models.CharField(max_length=50, verbose_name='Майл')),
                ('registration_time', models.TimeField(verbose_name='Дата')),
            ],
        ),
    ]
