# Generated by Django 4.2.2 on 2023-06-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Ponko_user',
        ),
    ]
